site:
  title: My API Document
  start_page: docs::index.adoc

content:
  sources:
    - url: https://github.com/adarsh-bm12/antora-docs-suchitra.git
      branches: main   # Adjust branch name if needed
      start_path: docs  # Change if your AsciiDoc files are in a different folderAdjust this based on your folder structure

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

runtime:
  fetch: true


output:
  dir: /var/www/html


