# This action rebuilds the docs whenever there is a change (push),
# and deplys it automatically on GitHub pages (the branch gh-pages).
#
name: Build and Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'

      - run: npm install
      - run: npx antora antora-playbook.yml --to-dir=html --url=https://vebholic.github.io/docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages    # The branch the action should deploy to.
          folder: html        # The folder the action should deploy.
